import { z } from 'zod';

/**
 * Layer C input-takeover contract (US-28, FR-B4) — shared by BOTH apps.
 *
 * The web control UI produces these CDP-shaped input intents from DOM
 * pointer/keyboard events; the orchestrator's `InputTakeoverController` consumes
 * them and dispatches CDP `Input.*` events to the session's isolated Chrome.
 * Because the intent crosses the app boundary (rides the `screencast:<id>` WS
 * channel when the user is in control), it lives here in `@flock/shared` — never
 * duplicated in either app.
 *
 * @see https://chromedevtools.github.io/devtools-protocol/tot/Input/
 */

/** CDP `Input.dispatchMouseEvent` params (the subset takeover forwards). */
export const CdpMouseEventParams = z.object({
  type: z.enum(['mousePressed', 'mouseReleased', 'mouseMoved', 'mouseWheel']),
  /** X relative to the top-left of the (screencast) viewport, CSS px. */
  x: z.number(),
  /** Y relative to the top-left of the (screencast) viewport, CSS px. */
  y: z.number(),
  button: z.enum(['none', 'left', 'middle', 'right', 'back', 'forward']).optional(),
  clickCount: z.number().int().optional(),
  /** Modifier bitfield (Alt=1, Ctrl=2, Meta=4, Shift=8). */
  modifiers: z.number().int().optional(),
  /** Wheel horizontal delta (mouseWheel only). */
  deltaX: z.number().optional(),
  /** Wheel vertical delta (mouseWheel only). */
  deltaY: z.number().optional(),
});
export type CdpMouseEventParams = z.infer<typeof CdpMouseEventParams>;

/** CDP `Input.dispatchKeyEvent` params (the subset takeover forwards). */
export const CdpKeyEventParams = z.object({
  type: z.enum(['keyDown', 'keyUp', 'rawKeyDown', 'char']),
  /** Modifier bitfield (Alt=1, Ctrl=2, Meta=4, Shift=8). */
  modifiers: z.number().int().optional(),
  /** DOM key, e.g. 'a', 'Enter', 'ArrowLeft'. */
  key: z.string().optional(),
  /** DOM code, e.g. 'KeyA', 'Enter'. */
  code: z.string().optional(),
  /** Windows virtual key code (when known). */
  windowsVirtualKeyCode: z.number().int().optional(),
  /** Text generated by the keystroke ('char' / printable keyDown). */
  text: z.string().optional(),
});
export type CdpKeyEventParams = z.infer<typeof CdpKeyEventParams>;

/**
 * One forwarded user-input intent — discriminated on `kind`. `mouse` carries one
 * mouse/scroll event (scroll is `type: 'mouseWheel'`); `key` carries one key
 * event. This is the wire payload the web side sends and the orchestrator
 * dispatches to CDP while the user holds control.
 */
export const InputIntent = z.discriminatedUnion('kind', [
  z.object({ kind: z.literal('mouse'), event: CdpMouseEventParams }),
  z.object({ kind: z.literal('key'), event: CdpKeyEventParams }),
]);
export type InputIntent = z.infer<typeof InputIntent>;
